clock = """<script>
    import {onDestroy} from "svelte";

    /**
     * Returns the current 12-hour timestamp
     */
    function get_timestamp() {
        const date = new Date();

        let hours = date.getHours();
        hours = hours > 12 ? hours - 12 : hours;
        hours = hours.toString().padStart(2, "0");

        const minutes = date
            .getMinutes()
            .toString()
            .padStart(2, "0");
        const seconds = date
            .getSeconds()
            .toString()
            .padStart(2, "0");

        const period = date.getHours() >= 12 ? "pm" : "am";

        return `${hours}:${minutes}:${seconds} ${period}`;
    }

    // First, we need to initialize our clock with current time
    let timestamp = get_timestamp();

    // Then, we need to update the clock every second
    const identifier = setInterval(() => {
        timestamp = get_timestamp();
    }, 1000);

    // Finally, clear our interval, when the Component is cleaned up
    onDestroy(() => {
        clearInterval(identifier);
    });
</script>

<h1>
    {timestamp}
</h1>
"""